### ISSUE TITLE
Can I build for x86_64 on an arm64 device?

### ISSUE THREAD

**Issue by TechStudent11** [joshiemoore/snakeware#164]
Just a question, can I build for x86_64 on an arm64 device?

_Originally posted by @TechStudent11 in https://github.com/joshiemoore/snakeware/issues/162#issuecomment-939354882_

**Comment by joshiemoore** [comment]
Cross-compilation should work fine, that's a big part of what buildroot does. Just as we can build images targeting the RPi on x86, you should be able to build for x86 from an ARM host.

I'm closing this because I just enabled the "Discussions" tab so people can ask questions there instead of opening issues.
