### ISSUE TITLE
Build_all.sh fails

### ISSUE THREAD

**Issue by shazz** [joshiemoore/snakeware#19]
Using Ubuntu 18.04, it downloaded a lot of things then crashes with:

```
...
usr/share/man/man1/python3.1 -> python3.8.1
usr/share/man/man1/python3.8.1

sent 326.07M bytes  received 170.24K bytes  217.49M bytes/sec
total size is 325.30M  speedup is 1.00
Installing for i386-pc platform.
grub-install: error: hostdisk//dev/loop0 appears to contain a squash4 filesystem which isn't known to reserve space for DOS-style boot.  Installing GRUB there could result in FILESYSTEM DESTRUCTION if valuable data is overwritten by grub-setup (--skip-fs-probe disables this check, use at your own risk).
umount: /mnt: not mounted.
loop deleted : /dev/loop25
```

**Comment by joshiemoore** [comment]
It failed because there is already something mounted for /dev/loop0. If you look at the last line, kpartx actually created a loop device for the disk image at /dev/loop25, but the script assumes /dev/loop0.

I recommend against trying to build your own image for now, we are going to be switching to buildroot for the build system and then it will work much better on people's systems that aren't mine.

**Comment by shazz** [comment]
Ok! Makes sense!
