### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by joshiemoore** [joshiemoore/snakeware#71]
Currently snakeware boots as a "Live USB" and user data does not persist between boots. We need a good way to store user data persistently.

I really like the idea of having a "ROM partition" of a few hundred MB where the snakeware distro is installed (this would allow different snakeware versions to be swapped easily just by overwriting the partition), and a separate "user partition" which fills the rest of the medium and can be used to store scripts, data, etc. This partition would be mounted and changedir'd to on boot.

I'm going to be the one that works on this, but ideas are welcome if anyone has any

**Comment by Admicos** [comment]
On Thu Jun 4, 2020 at 4:28 PM +03, Josh Moore wrote:
> Currently snakeware boots as a "Live USB" and user data does not persist
> between boots. We need a good way to store user data persistently.
>
> I really like the idea of having a "ROM partition" of a few hundred MB
> where the snakeware distro is installed (this would allow different
> snakeware versions to be swapped easily just by overwriting the
> partition), and a separate "user partition" which fills the rest of the
> medium and can be used to store scripts, data, etc. This partition would
> be mounted and changedir'd to on boot.

Instead of a ROM "partition", snakeware could just be built as a read-only 
initramfs, which I got working on a local branch.

That way, snakeware doesn't need to be installed to work, can run from a 
live USB or CD, and probably will be small enough that the user can use
the USB stick for more than just snakeware.

We could have a menu on boot that asks for a data partition to mount, or
create a temporary ramdisk if persistence isn't required by the user.

That way, we wouldn't need a complex installer or something like that.

> I'm going to be the one that works on this, but ideas are welcome if
> anyone has any

I already have a readonly live iso configuration I can share if you want 
to build on top, but it's tangled with some other random experiments, so
I'm not sure how useful that would be.

**Comment by Admicos** [comment]
I've pushed the local branch I talked about in the above comment over to [my fork in the experiments branch](https://github.com/Admicos/snakeware/commits/experiments).

It uses the build system I made in PR 30, but I assume it shouldn't be that hard to port over if neccesary

**Comment by alexandruavadanii** [comment]
Some random thoughts on this, mostly derived from the idea of supporting UEFI systems.
Note that most current x86 machines currently support both BIOS and UEFI, most aarch64 - not Raspberry Pi natively, but that's an outlier and I won't go into details about it here - support _only_ UEFI.

For UEFI systems, the disk image (or ISO) should use GPT (as opposed to currently using MBR) and have 1 partition formatted as FAT (also known as the ESP, or EFI System Partition).
Most OSes choose to store the EFI-compatible grub on the ESP, which will load the kernel/initramfs from the same ESP partition or from a different ext/xfs/whatever root partition.

To align with these requirements, the disk could be layed out like this:
- for x86, use a hybrid GPT/MBR partition table; while for aarch64 just GPT would be enough;
- have a small FAT partition with the bootloader (grub) and kernel/initramfs - this will work with either BIOS or UEFI (only one of the grub-pc or grub-efi-amd64 will be used, so we'd have to build different images for x86 BIOS and x86 UEFI systems);
- have another (ext4?) partition for persistent storage;
